version: "3.8"

services:
  pg-usuario:
    image: postgres:14.5
    container_name: pg-usuario
    restart: unless-stopped
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: db_usuario
      POSTGRES_PASSWORD: PGUsuario111
      TZ: America/Lima
      PGTZ: America/Lima
    volumes:
      - /Users/marcolopez/Workspace/volumes/pg-usuario:/var/lib/postgresql/data
      - ./scripts/pg_usuario_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

networks:
  default:
    external: true
    name: licencia-net
