version: "3.8"

services:
  pg-cliente:
    image: docker.io/bitnami/postgresql:14.7.0
    container_name: pg-cliente
    restart: unless-stopped
    ports:
    - "35432:5432"
    environment:
      POSTGRES_DB: db_cliente
      POSTGRES_PASSWORD: PGCliente111
      TZ: America/Lima
      PGTZ: America/Lima
    volumes:
      - /Users/marcolopez/Workspace/volumes/pg-cliente:/var/lib/postgresql/data
      - ./scripts/pg_cliente_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

networks:
  default:
    external: true
    name: licencium-net
