version: "3.8"

services:
  pg-licencia:
    image: docker.io/bitnami/postgresql:14.7.0
    container_name: pg-licencia
    restart: unless-stopped
    ports:
    - "25432:5432"
    environment:
      POSTGRES_DB: db_licencia
      POSTGRES_PASSWORD: PGLicencia111
      TZ: America/Lima
      PGTZ: America/Lima
    volumes:
      - /Users/marcolopez/Workspace/volumes/pg-licencia:/var/lib/postgresql/data
      - ./scripts/pg_licencia_init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

networks:
  default:
    external: true
    name: licencium-net
