version: "3.8"

services:
  zipkin-server:
    image: openzipkin/zipkin:2.24.0
    container_name: zipkin-server
    ports:
      - "9411:9411"
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - default

networks:
  default:
    external: true
    name: licencium-net
