version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9098:9090"
    volumes:
      - ./prometheus/config/:/etc/prometheus/
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - default

  grafana:
    image: grafana/grafana-oss:8.5.22
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password1234
      - GF_SERVER_DOMAIN=localhost
    networks:
      - default

networks:
  default:
    external: true
    name: licencium-net
