scrape_configs:

  - job_name: 'Usuario Service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['192.168.100.14:8001']
        labels:
          application: 'Usuario Service Microservice'
